Feature lesson6
polosbl/HerokuApp pull request #1
Opened 2021-05-02 17:49 UTC by polosbl

2021-05-03 10:04 UTC, vchesnakoutest requested changes
please make fixes

2021-05-03 10:04 UTC, vchesnakoutest commented on .idea/vcs.xml
> +</project>
файлы из папки  .idea коммитать не надо

2021-05-03 10:04 UTC, vchesnakoutest commented on src/test/java/tests/AddRemoveElementsTest.java
> +        }
т.к. основная идея этого теста - проверить нажатие на кнопку Delete , то ассерты на то, что эти кнопки показаны в принципе лишние. Если по какой-то причине кнопки не будет - то свалиться exception.

2021-05-03 10:04 UTC, vchesnakoutest commented on src/test/java/tests/CheckboxesTest.java
> +        checkbox = driver.findElement(By.xpath("//*[@id='checkboxes']/*[@type='checkbox'][2]"));
лучше писать в одну строку:
WebElement checkbox = driver.findElement(By.xpath("//*[@id='checkboxes']/*[@type='checkbox'][2]"));

проверь в остальных местах тоже

2021-05-03 10:04 UTC, vchesnakoutest commented on src/test/java/tests/HoverTest.java
> +        WebElement avatar = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div[1]/img"));
[@id=\"content\"]  - лучше писать [@id='content'] (без escaped characters)

(By.xpath("//*[@id=\"content\"]/div/div[1]/img") - попробуй переписать этот локатор без привязки к нескольким дивам. Там можно завязаться на src например

2021-05-03 10:04 UTC, vchesnakoutest commented on src/test/java/tests/HoverTest.java
> +        Assert.assertEquals(responseCode, 200, "Response code is incorrect");
а зачем тут проверка статус кода ? для тренировки ?)

2021-05-03 10:04 UTC, vchesnakoutest commented on src/test/java/tests/HoverTest.java
> +        WebElement avatar = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div[2]/img"));
не надежный локатор

2021-05-03 10:04 UTC, vchesnakoutest commented on src/test/java/tests/HoverTest.java
> +        WebElement username = driver.findElement(By.xpath("//*[@id=\"content\"]/div/div[2]/div/h5"));
не надежный локатор

2021-05-04 15:19 UTC, polosbl commented on src/test/java/tests/HoverTest.java
> +        Assert.assertEquals(responseCode, 200, "Response code is incorrect");
в домашке есть задание: проверка что нет 404 ошибки)

2021-05-04 15:23 UTC, merged